import React from "react";
import "@/assets/styles/global.scss";

import FontRoboto from "@/config/font";
import BaseProvider from "@/components/BaseProvider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  session
}: {
  children: React.ReactNode;
  session: any
}) {
  return (
    <html lang="en">
      <BaseProvider session={session} >
        <body className={FontRoboto.className}>{children}</body>
      </BaseProvider>
    </html>
  );
}
