import { Roboto } from "next/font/google";
import RootStyleRegistry from "./emotion";

import "./globals.css";

export const metadata = {
  title: "React Next App with Auth + Simple + Complex",
  description: "Generated by create next app",
};

const roboto = Roboto({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

// const theme = createTheme({
//   palette: {
//     secondary: {
//       main: colors.orange[500]
//     }
//   }
// });

export default function RootLayout({
  children,
}: {
  children: JSX.Element;
}) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
        <RootStyleRegistry>{children}</RootStyleRegistry>
      </body>
    </html>
  );
}
