"use client";

import React from "react";
import { ThemeProvider } from "@mui/material";
import { CacheProvider, EmotionCache } from "@emotion/react";
import "@/assets/styles/global.scss";

import FontRoboto from "@/config/font";
import createEmotionCache from "@/config/createEmotionCache";
import theme from "@/config/theme";

const clientSideEmotionCache = createEmotionCache();

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  emotionCache = clientSideEmotionCache,
}: {
  children: React.ReactNode;
  emotionCache?: EmotionCache;
}) {
  return (
    <html lang="en">
      <CacheProvider value={emotionCache}>
        <ThemeProvider theme={theme}>
          <body className={FontRoboto.className}>{children}</body>
        </ThemeProvider>
      </CacheProvider>
    </html>
  );
}
