import { Button, CircularProgress } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  return (
    <main>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <h1>Working well</h1>

      <CircularProgress color="secondary" />

      <Button variant="contained">Contained</Button>
    </main>
  );
};

export default Home;
